### ISSUE TITLE
TODO: package.json: `"name": "docs"`

### ISSUE THREAD

**Issue by pabloqpacin** [pabloqpacin/pabloqpacin.github.io#2]
- [ ] Editar archivos `docs/package.json` y `docs/package-lock.json`
- [ ] Cambiar el nombre `docs` por `pabloqpacin.github.io`
- [ ] ¿Consecuencias? ¿Papel del archivo? ¿Conflictos al cambiar "sin más"?

**Comment by pabloqpacin** [comment]
yeah so it shouldn't just be a big deal. Closing issue aye
